<%-- 
    Document   : cse-table-users
    Created on : 03.05.2014, 13:54:34
    Author     : oneplayer
--%>

<h3>Users list</h3>
<form role="form">
    <table class="table table-striped table-hover nomargin">
        <tr>
            <td>
                <b>User's id</b>
            </td>
            <td>
                <b>e-mail</b>
            </td>
            <td>
                <b>Role</b>
            </td>
            <td>
                <b>Firstname</b>
            </td>
            <td>
                <b>Lastname</b>
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                312432
            </td>
            <td>
                someemail@gmail.com
            </td>
            <td>
                CU
            </td>
            <td>
                Andrey
            </td>
            <td>
                Ivanov
            </td>
        </tr>
        <tr>
            <td>
                <input type="text" class="form-control">
            </td>
            <td>
                <input type="text" class="form-control">
            </td>
            <td>
                <input type="text" class="form-control">
            </td>
            <td>
                <input type="text" class="form-control">
            </td>
            <td>
                <input type="text" class="form-control">
            </td>
        </tr>                
    </table>
    <button type="button" class="btn btn-default margin"><span class="glyphicon glyphicon-remove-circle"></span> Apply filter</button>
    <button type="button" class="btn btn-default margin"><span class="glyphicon glyphicon-remove-circle"></span> Clean filter</button>
</form>
