-- Generated by Oracle SQL Developer Data Modeler 3.1.3.706
--   at:        2014-04-06 00:32:01 EEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE Cables 
    ( 
     id NUMBER (7)  NOT NULL , 
     Circuit_id NUMBER (7)  NOT NULL , 
     Port_id NUMBER (12)  NOT NULL , 
     Service_Locations_id NUMBER (8)  NOT NULL 
    ) 
;



ALTER TABLE Cables 
    ADD CONSTRAINT Cable_PK PRIMARY KEY ( id ) ;



CREATE TABLE Circuits 
    ( 
     id NUMBER (7)  NOT NULL , 
     "Service Instance_id" NUMBER (3)  NOT NULL , 
     Port_id NUMBER (12)  NOT NULL 
    ) 
;



ALTER TABLE Circuits 
    ADD CONSTRAINT Circuit_PK PRIMARY KEY ( id ) ;



CREATE TABLE Device_Models 
    ( 
     id NUMBER (3)  NOT NULL , 
     Name VARCHAR2 (50) , 
     Characteristics VARCHAR2 (300) 
    ) 
;



ALTER TABLE Device_Models 
    ADD CONSTRAINT "Device Model_PK" PRIMARY KEY ( id ) ;



CREATE TABLE Devices 
    ( 
     id NUMBER (8)  NOT NULL , 
     "Provider Location_id" NUMBER (7)  NOT NULL , 
     "Device Model_id" NUMBER (3)  NOT NULL 
    ) 
;



ALTER TABLE Devices 
    ADD CONSTRAINT Device_PK PRIMARY KEY ( id ) ;



CREATE TABLE Locations 
    ( 
     id NUMBER (10)  NOT NULL , 
     pos_x NUMBER , 
     pos_y NUMBER , 
     address VARCHAR2 (200) 
    ) 
;



ALTER TABLE Locations 
    ADD CONSTRAINT Location_PK PRIMARY KEY ( id ) ;



CREATE TABLE Ports 
    ( 
     id NUMBER (12)  NOT NULL , 
     Device_id NUMBER (8)  NOT NULL , 
     free CHAR (1) 
    ) 
;



ALTER TABLE Ports 
    ADD CONSTRAINT Ports_PK PRIMARY KEY ( id ) ;



CREATE TABLE Prices 
    ( 
     id NUMBER (5)  NOT NULL , 
     "Provider Location_id" NUMBER (7)  NOT NULL , 
     Service_id NUMBER (3)  NOT NULL , 
     price NUMBER 
    ) 
;



ALTER TABLE Prices 
    ADD CONSTRAINT Price_PK PRIMARY KEY ( id ) ;



CREATE TABLE Provider_Locations 
    ( 
     id NUMBER (7)  NOT NULL , 
     Location_id NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE Provider_Locations 
    ADD CONSTRAINT Provider_Locations_PK PRIMARY KEY ( id ) ;



CREATE TABLE Roles 
    ( 
     id NUMBER (3)  NOT NULL , 
     Name VARCHAR2 (20) 
    ) 
;



ALTER TABLE Roles 
    ADD CONSTRAINT Roles_PK PRIMARY KEY ( id ) ;



CREATE TABLE Scenarios 
    ( 
     id NUMBER (3)  NOT NULL , 
     Name VARCHAR2 (30) 
    ) 
;



ALTER TABLE Scenarios 
    ADD CONSTRAINT Scenarios_PK PRIMARY KEY ( id ) ;



CREATE TABLE Service_Instances 
    ( 
     id NUMBER (3)  NOT NULL , 
     User_id NUMBER (3)  NOT NULL , 
     Service_id NUMBER (3)  NOT NULL , 
     Provider_Location_id NUMBER (7)  NOT NULL , 
     Service_Order_id NUMBER (8)  NOT NULL , 
     Service_Location_id NUMBER (8)  NOT NULL , 
     Status VARCHAR2 (15) 
    ) 
;



ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Instances_PK PRIMARY KEY ( id ) ;



CREATE TABLE Service_Locations 
    ( 
     id NUMBER (8)  NOT NULL , 
     Location_id NUMBER (10)  NOT NULL , 
     Provider_Location_id NUMBER (7)  NOT NULL 
    ) 
;



ALTER TABLE Service_Locations 
    ADD CONSTRAINT Service_Locations_PK PRIMARY KEY ( id ) ;



CREATE TABLE Service_Orders 
    ( 
     id NUMBER (8)  NOT NULL , 
     enterDate DATE , 
     procesDate DATE , 
     completeDate DATE , 
     User_id NUMBER (3)  NOT NULL , 
     Service_id NUMBER (3)  NOT NULL , 
     Provider_Location_id NUMBER (7)  NOT NULL , 
     Service_Location_id NUMBER (8)  NOT NULL , 
     Status VARCHAR2 (15) 
    ) 
;



ALTER TABLE Service_Orders 
    ADD CONSTRAINT Service_Order_PK PRIMARY KEY ( id ) ;



CREATE TABLE Services 
    ( 
     id NUMBER (3)  NOT NULL , 
     Name VARCHAR2 (50) , 
     Description VARCHAR2 (300) 
    ) 
;



ALTER TABLE Services 
    ADD CONSTRAINT Service_PK PRIMARY KEY ( id ) ;



CREATE TABLE Tasks 
    ( 
     id NUMBER (12)  NOT NULL , 
     Workflow_id NUMBER (8)  NOT NULL , 
     User_id NUMBER (3)  NOT NULL , 
     type VARCHAR2 (15) , 
     Status VARCHAR2 (15) , 
     Role_id NUMBER (3)  NOT NULL 
    ) 
;



ALTER TABLE Tasks 
    ADD CONSTRAINT Task_PK PRIMARY KEY ( id ) ;



CREATE TABLE Users 
    ( 
     id NUMBER (3)  NOT NULL , 
     Name VARCHAR2 (30) , 
     email VARCHAR2 (20) , 
     login VARCHAR2 (20) , 
     password VARCHAR2 (20) , 
     blocked CHAR (1) , 
     Role_id NUMBER (3)  NOT NULL 
    ) 
;



ALTER TABLE Users 
    ADD CONSTRAINT User_PK PRIMARY KEY ( id ) ;



CREATE TABLE Workflows 
    ( 
     id NUMBER (8)  NOT NULL , 
     Service_Order_id NUMBER (8)  NOT NULL , 
     Scenario_id NUMBER (3)  NOT NULL 
    ) 
;



ALTER TABLE Workflows 
    ADD CONSTRAINT Workflow_PK PRIMARY KEY ( id ) ;




ALTER TABLE Cables 
    ADD CONSTRAINT Cable_Circuit_FK FOREIGN KEY 
    ( 
     Circuit_id
    ) 
    REFERENCES Circuits 
    ( 
     id
    ) 
;


ALTER TABLE Cables 
    ADD CONSTRAINT Cable_Ports_FK FOREIGN KEY 
    ( 
     Port_id
    ) 
    REFERENCES Ports 
    ( 
     id
    ) 
;


ALTER TABLE Cables 
    ADD CONSTRAINT Cables_Service_Locations_FK FOREIGN KEY 
    ( 
     Service_Locations_id
    ) 
    REFERENCES Service_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Circuits 
    ADD CONSTRAINT Circuit_Ports_FK FOREIGN KEY 
    ( 
     Port_id
    ) 
    REFERENCES Ports 
    ( 
     id
    ) 
;


ALTER TABLE Circuits 
    ADD CONSTRAINT Circuit_Service_Instance_FK FOREIGN KEY 
    ( 
     "Service Instance_id"
    ) 
    REFERENCES Service_Instances 
    ( 
     id
    ) 
;


ALTER TABLE Devices 
    ADD CONSTRAINT Device_Device_Model_FK FOREIGN KEY 
    ( 
     "Device Model_id"
    ) 
    REFERENCES Device_Models 
    ( 
     id
    ) 
;


ALTER TABLE Devices 
    ADD CONSTRAINT Device_Provider_Location_FK FOREIGN KEY 
    ( 
     "Provider Location_id"
    ) 
    REFERENCES Provider_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Ports 
    ADD CONSTRAINT Ports_Device_FK FOREIGN KEY 
    ( 
     Device_id
    ) 
    REFERENCES Devices 
    ( 
     id
    ) 
;


ALTER TABLE Prices 
    ADD CONSTRAINT Price_Provider_Location_FK FOREIGN KEY 
    ( 
     "Provider Location_id"
    ) 
    REFERENCES Provider_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Prices 
    ADD CONSTRAINT Price_Service_FK FOREIGN KEY 
    ( 
     Service_id
    ) 
    REFERENCES Services 
    ( 
     id
    ) 
;


ALTER TABLE Provider_Locations 
    ADD CONSTRAINT Provider_Locations_Loc_FK FOREIGN KEY 
    ( 
     Location_id
    ) 
    REFERENCES Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Inst_Provider_Loc_FK FOREIGN KEY 
    ( 
     Provider_Location_id
    ) 
    REFERENCES Provider_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Inst_Service_Loc_FK FOREIGN KEY 
    ( 
     Service_Location_id
    ) 
    REFERENCES Service_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Inst_Service_Ord_FK FOREIGN KEY 
    ( 
     Service_Order_id
    ) 
    REFERENCES Service_Orders 
    ( 
     id
    ) 
;


ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Instances_Services_FK FOREIGN KEY 
    ( 
     Service_id
    ) 
    REFERENCES Services 
    ( 
     id
    ) 
;


ALTER TABLE Service_Instances 
    ADD CONSTRAINT Service_Instances_Users_FK FOREIGN KEY 
    ( 
     User_id
    ) 
    REFERENCES Users 
    ( 
     id
    ) 
;


ALTER TABLE Service_Locations 
    ADD CONSTRAINT Service_Loc_Provider_Loc_FK FOREIGN KEY 
    ( 
     Provider_Location_id
    ) 
    REFERENCES Provider_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Locations 
    ADD CONSTRAINT Service_Locations_Locations_FK FOREIGN KEY 
    ( 
     Location_id
    ) 
    REFERENCES Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Orders 
    ADD CONSTRAINT Service_Order_ProvLoc_FK FOREIGN KEY 
    ( 
     Provider_Location_id
    ) 
    REFERENCES Provider_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Orders 
    ADD CONSTRAINT Service_Order_ServLoc_FK FOREIGN KEY 
    ( 
     Service_Location_id
    ) 
    REFERENCES Service_Locations 
    ( 
     id
    ) 
;


ALTER TABLE Service_Orders 
    ADD CONSTRAINT Service_Order_Service_FK FOREIGN KEY 
    ( 
     Service_id
    ) 
    REFERENCES Services 
    ( 
     id
    ) 
;


ALTER TABLE Service_Orders 
    ADD CONSTRAINT Service_Order_User_FK FOREIGN KEY 
    ( 
     User_id
    ) 
    REFERENCES Users 
    ( 
     id
    ) 
;


ALTER TABLE Tasks 
    ADD CONSTRAINT Tasks_Roles_FK FOREIGN KEY 
    ( 
     Role_id
    ) 
    REFERENCES Roles 
    ( 
     id
    ) 
;


ALTER TABLE Tasks 
    ADD CONSTRAINT Tasks_Users_FK FOREIGN KEY 
    ( 
     User_id
    ) 
    REFERENCES Users 
    ( 
     id
    ) 
;


ALTER TABLE Tasks 
    ADD CONSTRAINT Tasks_Workflows_FK FOREIGN KEY 
    ( 
     Workflow_id
    ) 
    REFERENCES Workflows 
    ( 
     id
    ) 
;


ALTER TABLE Users 
    ADD CONSTRAINT User_Roles_FK FOREIGN KEY 
    ( 
     Role_id
    ) 
    REFERENCES Roles 
    ( 
     id
    ) 
;


ALTER TABLE Workflows 
    ADD CONSTRAINT Workflow_Scenarios_FK FOREIGN KEY 
    ( 
     Scenario_id
    ) 
    REFERENCES Scenarios 
    ( 
     id
    ) 
;


ALTER TABLE Workflows 
    ADD CONSTRAINT Workflow_Service_Order_FK FOREIGN KEY 
    ( 
     Service_Order_id
    ) 
    REFERENCES Service_Orders 
    ( 
     id
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            17
-- CREATE INDEX                             0
-- ALTER TABLE                             45
-- CREATE VIEW                              0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE STRUCTURED TYPE                   0
-- CREATE COLLECTION TYPE                   0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
